import React from 'react';
import Head from 'next/head';
import { Container, Typography } from '@mui/material';
import Link from 'next/link';
import styles from './IndexLayout.module.css';

const IndexLayout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>My Movie Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <hr />
      <footer>
        <Container style={{ padding: '1rem 0' }}>
          <Typography variant="body2" color="textSecondary">
            &copy; {new Date().getFullYear()} XXX Company Ltd | All Rights Reserved |{' '}
            <Link href="#" className={styles.link}>
              Terms and Conditions
            </Link>{' '}
            |{' '}
            <Link href="#" className={styles.link}>
              Privacy Policy
            </Link>
          </Typography>
        </Container>
      </footer>
    </>
  );
};

export default IndexLayout;
