import React from 'react';
import Head from 'next/head';
import { Container } from '@mui/material';

const IndexLayout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>My Movie Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <hr />
      <footer>
        <Container style={{ padding: '1rem 0' }}>
          <span
            style={{
              fontFamily: 'Roboto',
            }}
          >
            copyright XXX Inc.
          </span>
        </Container>
      </footer>
    </>
  );
};

export default IndexLayout;
